---
title: 'STA 326 2.0: Online Helpdesk - 2020'
author: "Dr Thiyanga Talagala"
date: "06/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r, comment=NA, message=FALSE, warning=FALSE}
library(coronavirus)
library(tidyverse)
library(magrittr)

```

# Question 1: Plotting negative values

## Method 1: Discontinuity Point

```{r, comment=NA, fig.pos="center", fig.cap="Figure 1: Time series plot of recovered cases (discontinuity represents missing values/ negative values)"}

spain_corona <- coronavirus %>% filter(country == "Spain")
recovered_spain_corona <- spain_corona %>% filter(type=="confirmed")
summary(recovered_spain_corona)
# code missing values to NA
recovered_spain_corona <- recovered_spain_corona %>% mutate(cases = replace(cases, which(cases < 0), NA))
summary(recovered_spain_corona) # Now you can see in the summary table there are no negative values instead we have NA's
ggplot(recovered_spain_corona, aes(x=date, y=cases)) +
  geom_line() # Now you can see discontinuity in the line.
```

## Method 2: Impute missing value

```{r,comment=NA, message=FALSE, fig.cap="Figure 2: Time series plot of recovered cases (imputed values are shown in red.)"}
# Locate missing value
which(is.na(recovered_spain_corona$cases)) # Using base R
# I use the average of the 93rd and the 95th to calculate the missing value/negative value.
recovered_spain_corona$cases[94] = mean(c(recovered_spain_corona$cases[93], recovered_spain_corona$cases[95]))
length(recovered_spain_corona$cases)
#  I add a column col that indicates desired colour.
recovered_spain_corona$col <- as.factor(c(rep("black", 92),rep("red", 2), rep("black", 112-94)))
summary(recovered_spain_corona)
ggplot(recovered_spain_corona, aes(x=date, y=cases)) +
  geom_line(aes(colour=col, group=1)) + 
  scale_colour_identity()

```


# Question 2: Example for geom_freqpoly

# Frequency polygons

```{r, comment=NA, message=FALSE, warning=FALSE, fig.cap="Figure 3: Distribution of number of recovered cases"}
ggplot(recovered_spain_corona, aes(cases)) +
  geom_freqpoly(bins = 9)
```

# Histogram

```{r, comment=NA, fig.cap="Figure 4: Distribution of number of recovered cases"}
ggplot(recovered_spain_corona, aes(cases)) +
  geom_histogram(bins = 9, col="white", alpha=0.5)
```

# Histogram + Frequency polygon

A frequency polygon is a graph constructed by joining the midpoints of each interval or bin.

```{r, comment=NA, fig.cap="Figure 5: Distribution of number of recovered cases"}
ggplot(recovered_spain_corona, aes(cases)) +
  geom_histogram(bins = 9, col="white", alpha=0.5) + 
  geom_freqpoly(bins = 9, col="red")
```

# Question 3: Multiple Time Series

```{r, comment=NA}
us_corona <- coronavirus %>% filter(country == "US")
head(us_corona)
ggplot(us_corona, aes(x=date, y=cases, col=type)) + geom_line()
```

