---
title: "Organize your priorities using CalendaR package in R"
date: "2021-02-09"
summary: "Maintaining a calendar to organize your events allows for having more smooth and productive day. In this post, I will show you some basic functionalities in CalendaR package."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

It is important to maintain a calendar in order to budget your time well.  In this post, I will show you some basic functionalities of `calendaR` package in R. You can find more information [here](https://r-coder.com/calendar-plot-r/).

### Load package

```{r, comment=NA, message=FALSE}
library(calendR)
```

### 1. Load calendar - 2021

```{r, comment=NA, message=FALSE}
calendR(year = 2021, # Set the year
        start = "M",  # Set the first day of the calendar week as Monday (optional argument)
        special.days = "weekend", # Colour  weekends (optional argument)
        special.col = "#b2df8a") # background colour for weekends (optional arguments)
```


### 2. Mark events

```{r, comment=NA, message=FALSE}
events <- rep(NA, 365)

# Event dates
events[100:200] <- "2nd semester"
events[213:240] <- "Examination"
events[300:310] <- "Conference"
events[359] <- "Christmas" 

calendR(year = 2021,
        special.days = events,
        start = "M", 
        special.col = c("#1b9e77", "#d95f02", "#7570b3", "#e7298a"),
        legend.pos = "right") 
```


### 3. Monthly plan

```{r, comment=NA}
calendR(year = 2021, month = 2,
          text = c("Exam", "Exam", # Event labels
                 "RLadies"), 
        text.pos = c(18, 20, 23), # Events dates texts 
        text.size = 4.5,          # Font size of the labels
        text.col = "#1b9e77")
```


