---
title: "Happy Women in Maths Day - 12 May 2020"
author: Thiyanga Talagala
date: '2020-05-13'
categories: [Mathematics, Nature, STEM, Science, Women in STEM]
tags: [Mathematics, Nature, STEM, Science, Women in STEM]
summary: "Nature is my biggest inspiration for my love and passion for mathematics."
---

Nature is my biggest inspiration for my love and passion for mathematics. It is amazing to see how these leaves follow geometry to ensure the surface is optimized for the absorption of sunlight. Indeed, nature is a good Mathematician. All its presentations are well calculated and designed. I see a great artist or a designer inside every Mathematician. Maths will teach you how to hold your brush, how to mix your paints and how to manage your tools for a great design. 

Enjoy the spirit of Mathematics!



<blockquote class="twitter-tweet"><p lang="en" dir="ltr">&quot;Nature is my biggest inspiration for my love and passion for mathematics&quot; - meet Dr Thiyanga Talagala <a href="https://twitter.com/thiyangt?ref_src=twsrc%5Etfw">@thiyangt</a> - a former ACEMS student <a href="https://twitter.com/MonashEBS?ref_src=twsrc%5Etfw">@MonashEBS</a> and now a lecturer at <a href="https://twitter.com/usjp?ref_src=twsrc%5Etfw">@usjp</a> - watch her <a href="https://twitter.com/hashtag/WomenInMaths?src=hash&amp;ref_src=twsrc%5Etfw">#WomenInMaths</a> day video: <a href="https://t.co/wPwAcyVunm">https://t.co/wPwAcyVunm</a> <a href="https://twitter.com/hashtag/WomenInSTEM?src=hash&amp;ref_src=twsrc%5Etfw">#WomenInSTEM</a> <a href="https://twitter.com/MonashBusiness?ref_src=twsrc%5Etfw">@MonashBusiness</a> <a href="https://twitter.com/hashtag/may12wim?src=hash&amp;ref_src=twsrc%5Etfw">#may12wim</a> <a href="https://t.co/xkWtOb4Rzu">pic.twitter.com/xkWtOb4Rzu</a></p>&mdash; ğ˜¼ğ˜¾ğ™€ğ™ˆğ™ (@ACEMathStats) <a href="https://twitter.com/ACEMathStats/status/1259826338623520768?ref_src=twsrc%5Etfw">May 11, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Acknowledgement: 

Australian Mathematical Society

ACEMS: Australian Research Council Centre of Excellence For Mathematical and Statistical Frontiers

